### PR TITLE
fix for a scenario where the carousel does not show up in Android app…

### PR DESCRIPTION
**Pull request by farcasclaudiu**
… (due the fact canSetLayout variable remains set to false and control does not get properly initialised).

### CODE REVIEW

**Comment by farcasclaudiu** [comment]
This is a sample that shows the issue with current nuget package.
https://github.com/farcasclaudiu/IssueCarousel

Regards,
Claudiu

**Comment by alexrainman** [comment]
Great, will take a look.

**Comment by AlariOis** [comment]
Fixed a problem I was having.

**Comment by jlgabbar** [comment]
When will this fix be available?

**Pull request closed without merging**
