### PR TITLE
added prev/next buttons

### PR DESCRIPTION
**Pull request by alexprigi**

### CODE REVIEW

**Comment by alexprigi** [comment]
Hi! 
This PR belongs to the issue(feature) https://github.com/alexrainman/CarouselView/issues/511
I added by my self the prev/next buttons that could be used instead or along with the arrow buttons in order to change page.
Hope you will merge ;)

**Comment by AviadKatani** [comment]
@alexprigi Hey there,
I have a real need to this feature of Next / Prev buttons, thing is I just don't know how to get the Nuget of this feature from. I'm currently using the main nuget and using it just like in the Demo.

How can I make the feature available as a NuGet? On the demo you have the plugin files in the same folder as the project but is there another way?

Thanks and sorry for the newbie questions :)

**Comment by alexprigi** [comment]
Hey there!

Actually I have never published something on nuget and I don't know how can
I help you... Furthermore I also don't think we could do it because of the
rights... This app belongs to alexrainman and I don't think is fair to
publish, in another repo, an app that someone else has developed.

But what you could do - and it's also what I did - is to fork the repo into
your github add it as submodule into your project, select my branch and
reference it (as the demo project).... I know that is not the most
beautiful solution....
Maybe you could push the owner of the repo to merge my branch..... so that
he will understand that also other users need this feature...

Let me know if you have other questions....
Alex

Il giorno dom 5 mag 2019 alle ore 11:24 Aviad <notifications@github.com> ha
scritto:

**Comment by AviadKatani** [comment]
Hi, thanks! now I have a better understanding.

What I meant is my app is using this nuget same way as the demo (MVVM). Can
I add Next / Prev button to it with the main version
of the CarouselView?

Thanks again for your help

**Comment by alexprigi** [comment]
I don't think that is possible....
You can not use nuget if you want to have the next/prev buttons...

Il giorno lun 6 mag 2019 alle ore 10:54 Aviad <notifications@github.com> ha
scritto:

> Hi, thanks! now I have a better understanding.
>
> What I meant is my app is using this nuget same way as the demo (MVVM). Can
> I add Next / Prev button to it with the main version
> of the CarouselView?
>
> Thanks again for your help
>

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. This will be supported.

**Comment by AviadKatani** [comment]
Hi Alexander,

Are there any news about that? You're going to upload the next/prev button
thing to Nuget so we can just remove the original and install yours?


‫בתאריך יום ג׳, 4 ביוני 2019 ב-19:25 מאת ‪Alexander Reyes‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by alexrainman** [comment]
Fully customizable prev/next buttons, based on templates, will be provided in next release so, i will not be merging this PR. Thank you for your support.

**Pull request closed without merging**
