### PR TITLE
Add Infinite feature and fix some minor issue

### PR DESCRIPTION
**Pull request by kanvuduc**
- Add infinite carousel
- Fix issues:
   - Carousel not shown: Make sure Element_SizeChanged called at least one

### CODE REVIEW

**Comment by alexrainman** [comment]
I cannot evaluate your pull request. It seems you override the entire files. Thanks a lot for the collaboration.

**Comment by alexrainman** [comment]
Can you break this in separated PR?

**Comment by kanvuduc** [comment]
We are using your libs in our project and our changes are in production already.

**Comment by kanvuduc** [comment]
We didn't override your files. That might be issue on merging.

**Comment by kanvuduc** [comment]
I checked that this is the way Github diff shows the changes. You could compare using Visual Studio for ease of comparison. We are currently using your code directly, but I think it's better to create a `pull request` then use the nuget :).

**Comment by alexrainman** [comment]
No, this not the way GitHub shows the changes. Normally it highlight in green the line or piece of code that changed. In your case is highlighting the entire thing, which is hard to understand.

Please, create separated PR for each fix/functionality. Start from scratch so only the pieces of code that changes are highlighted.

Thanks

**Comment by kanvuduc** [comment]
The code is copied from our production source code so there, it comes as a whole when published to Github.

I couldn't help to create separate pieces for you.

**Comment by alexrainman** [comment]
Thanks.

**Comment by kanvuduc** [comment]
Will you merge?

**Comment by alexrainman** [comment]
Only after you provide separated PR and me reviewing and evaluating the changes. Thanks

**Pull request closed without merging**
