### PR TITLE
Migration to .NET Standard 1.4

### PR DESCRIPTION
**Pull request by arnaudmaichac**
Hello,
I've been using your control for some months now and I just wanted to give a small contribution by migrating your project to .NET Standard 1.4 (.NET Standard 2.0 only works in UWP projects if you target the release 16299).

### CODE REVIEW

**Comment by alexrainman** [comment]
How di you make it work with 1.4 if Xamarin.Forms is compatible only with 2.0?

**Comment by arnaudmaichac** [comment]
Xamarin(.Forms) is compatible with all versions of .NET Standard: https://docs.microsoft.com/en-us/dotnet/standard/net-standard. 
.NET Standard 2.0 is now supported with Xamarin.Forms 2.4

**Comment by alexrainman** [comment]
Xamarin.Forms is not on that list. I tried before and it didn't work. in UWP it only works with 16299 release and still doesn't works or i don't know how to make it work. It says my OS is running previous version.

**Comment by arnaudmaichac** [comment]
Of course Xamarin.Forms is not on that list as it's an additional layer added on top of Xamarin.iOS, Xamarin.MacOS, Xamarin.Android and UWP. Once again, if you target .NET Standard 1.4, your plugin will work will all UWP SDK. Have a look at the plugins of James Montemagno, all of them target .NET Standard.

**Example:** https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/src/Geolocator.Plugin.Abstractions/Geolocator.Plugin.Abstractions.csproj

If you have a closer look at the pull request, you will see that the target version of the UWP Demo project is still set to 15063 and the min version to 10240. It compiles and works. Just download the code or clone the fork of your project from my repository: https://github.com/arnaudmaichac/CarouselView/tree/NetStandard

By targeting .NET Standard 2.0, you will have to set the target and min version of your UWP project to 16299.

**Comment by alexrainman** [comment]
I tried before and it didnt work. Will give it another shot.

**Comment by arnaudmaichac** [comment]
Happy to see you were able to target .NET Standard 1.4 in the version 5.0 👍

**Comment by alexrainman** [comment]
Yes, i did. Also i found out that the same Net.Standard binary works on PCL, so the plugin is backward compatible.

**Pull request closed without merging**
