### PR TITLE
Added support for different Views for same BindingContext

### PR DESCRIPTION
**Pull request by neurospeech**
In case, when we just want to display different View for the same data, we can provide `List<DataTemplate>` as `ItemsSource`, as `DataTemplate` does not have `BindingContext`, it just needs to inherit `BindingContext` of `CarouselView`.

Also added ability to change `Position` from MVVM binding.

### CODE REVIEW

**Comment by alexrainman** [comment]
I like the add-in for position but I don't get the first one. We have TemplateSelector to show different view for same data.

**Comment by neurospeech** [comment]
Problem with TemplateSelector requires extra code (also since you are overriding BindingContext to Item, it destroys purpose). For example, I can write a simple Xaml as follow... each page needs same BindingContext, I am just displaying data in different form. For example, I have an object of a Person, first page displays a full screen photo, second page displays a bio of person, third page displays contact information of the person.

```
<cv:CarouselView BindingContext="{Binding Person}">
    <cv:CarouselView.ItemsSource>
           <x:Array Type="{x:Type DataTemplate}>

                    <!-- Page1 Display Photo -->
                    <DataTemplate>
                            <Image Source="{Binding PhotoUrl}"/>
                    </DataTemplate>

                    <!-- Page2 Display Bio -->
                    <DataTemplate>
                            <Label FormattedString="{Binding Bio}"/>
                    </DataTemplate>

                    <!-- Page2 Display contact information -->
                    <DataTemplate>
                            <ScrollView..... 
                    </DataTemplate>

           </x:Array>
    </cv:CarouselView.ItemsSource>
</cv:CarouselView>
```

In this way, I can create different pages, all inside a Xaml, instead of creating C# class for TemplateSelector.

**Comment by alexrainman** [comment]
No no, i am not overriding BindingContext, i am assigning it that is not the same thing. The whole point of the architecture of the plugin is to have a source of non visual/UI objects that you can assign as binding context of any kind of view. They are completely decoupled. Thats why a TemplateSelector.

**Comment by alexrainman** [comment]
With your idea you are tying ItemsSource to UI elements.

**Comment by neurospeech** [comment]
Ok, do you have any better way of solving the UI I want to create? I just have one class, 

```
    public class Person{
          public string PhotoUrl {get;set;}
          public FormattedString Bio {get;set;}
          public ContactInfo ContactInfo {get;set;}
    }
```

I want each of them to display on separate page, this is the requirement.

**Comment by alexrainman** [comment]
Now i get what you want to do :)

**Comment by alexrainman** [comment]
I will release a new version including this functionality. Thanks

**Comment by alexrainman** [comment]
I will include this in next release. I had to manually add the changes as Im applying some extra fixes.

**Comment by alexrainman** [comment]
I am going to release a new version today which will put back the ability of declaring the entire Carousel in XAML (it was broken after i changed ItemsSource to support ObservableCollection).

You will be able to do this:

```
<cv:CarouselViewControl BindingContext="{Binding Person}">
    <cv:CarouselViewControl .ItemsSource>
           <x:Array Type="{x:Type View}>

                    <!-- Page1 Display Photo -->
                    <Image Source="{Binding PhotoUrl}"/>

                    <!-- Page2 Display Bio -->
                    <Label FormattedString="{Binding Bio}"/>

                    <!-- Page2 Display contact information -->
                    <Label FormattedString="{Binding Info}"/>

           </x:Array>
    </cv:CarouselViewControl .ItemsSource>
</cv:CarouselViewControl >
```

With each element inside the array rendered as a page :)

**Pull request closed without merging**
