### PR TITLE
Add AnimateTransition property and fix iOS PositionSelected calls

### PR DESCRIPTION
**Pull request by mikegottlieb**
Here are the changes we discussed in issue #47 

I didn't update the UWP project because I don't know anything about that, but I updated iOS and Android and tested them. I also added the dlls to my real application and verified that it fixed my issues there.

### CODE REVIEW

**Comment by alexrainman** [comment]
I will apply the fix manually as i already fixed the position selected plus items source issues.

**Comment by alexrainman** [comment]
Also, you are making changes where are not needed :)

**Comment by alexrainman** [comment]
We have a problem my friend. If we disable animation for SetCurrentPage in android, positionSelected is not called, so i wont add this property.

**Comment by alexrainman** [comment]
Or i will need small fix for it because i like it.

**Comment by mikegottlieb** [comment]
Just saw your changes. Thanks again!

**Comment by alexrainman** [comment]
Thank you for your collaboration :)

**Pull request closed without merging**
