### PR TITLE
Add Tizen backend

### PR DESCRIPTION
**Pull request by myroot**
* Support Tizen platform (tizen40)

image

### CODE REVIEW

**Comment by alexrainman** [comment]
@myroot this is excellent. My control has been merged into Xamarin.Forms master branch. I already let Xamarin.Forms team of your implementation and they will let you know how to do a pull request in their repository. Thanks.

**Comment by myroot** [comment]
@alexrainman Ok, I will also submit into Xamarin.Forms after merged to master branch but it seem not yet merged

**Comment by alexrainman** [comment]
@myroot there's a feature branch https://github.com/xamarin/Xamarin.Forms/tree/feature-carouselview you can make the pull request there. They already merged what i submitted and they will run unit and UI testing and also build a gallery with all the functionality the control offers.

**Comment by rmarinho** [comment]
@myroot you should branch the feature-carouselview branch and make a PR against that branch and I will accept

**Comment by myroot** [comment]
@alexrainman I hope to be merged in this project. Because Xamarin.Forms officially support Tizen since XF3.0. But many Apps yet used under 2.5 version
and also this project spreadly used on many apps. so i want to be merged it

**Pull request closed without merging**
