### PR TITLE
System.NullReferenceException: iOS only

### PR DESCRIPTION
**Pull request by DavidStrickland0**

### CODE REVIEW

**Comment by DavidStrickland0** [comment]
Started getting a Nullreference error in the Carsoul on a page that does not load its data till on appearing. Adding these null checks allowed the carsoul to load and then be populated with data later.

**Comment by alexrainman** [comment]
Will merge this and make it available in the upcoming release that will be out in a couple of days as soon as i solve an Android issue.

**Comment by alexrainman** [comment]
Can you confirm this issue is not happening in Android?

**Comment by alexrainman** [comment]
At least one of your fixes apply to Android also.

**Comment by DavidStrickland0** [comment]
Was not happening in android.  App ran fine on android but crached in the pagerenderer on iOS.

**Pull request merged**
