### PR TITLE
Tweak to Allow ItemsSource to be ViewModels

### PR DESCRIPTION
**Pull request by SteHiggins**
We are finishing off an app which uses CarouselView with an ItemsSource which is a collection of View Models.  This caused a memory leak in iOS.  As the app is near completion, we did not want to rewrite the app to provide a collection of Views (as the documentation suggests). I have tweaked the Carousel View to allow View Models in the ItemsSource.  
It is untested, except for on our app which works as desired.

Thanks to Alex Rainman for all the work you have put into maintaining this repo.

### CODE REVIEW

**Comment by clovs** [comment]
Someone can accept this PR?
I Really need this feature.
Please

Regards

**Comment by SteHiggins** [comment]
The ItemsSource-ViewModels fork is available on nuget at CarouselView.FormsPlugin.AllowViewModels.

**Comment by clovs** [comment]
Thanks @SteHiggins

**Comment by alexmartinezm** [comment]
Great job!

**Comment by alexrainman** [comment]
This tweak is not required to support ViewModels as items source. The only requirement is to provide an ItemTemplate to make it work.

**Comment by SteHiggins** [comment]
Yes - we had it working with ViewModels as ItemSource and an ItemTemplate set - this worked as expected.

However - iOS devices crashed (particularly older iOS devices) if the user swiped back and forth too many times.  

It turned out that it was a memory leak caused by the views not being disposed but new ones created as the user swiped back and forth.

This tweak solved this issue.

**Comment by alexrainman** [comment]
Got it. Including your fix, partially, with my own fix.

**Comment by SteHiggins** [comment]
Great.  Thanks for maintaining this repo.

**Comment by alexrainman** [comment]
I am working to catch up with all the issues and release a new version with bunch of new functionality, stability and performance fixes.

**Pull request closed without merging**
