### PR TITLE
Update CirclePageIndicator

### PR DESCRIPTION
**Pull request by Phenek**
Hey Boy,

Here there is an update of CirclePageIndicator, for Xam >= 3.5

Hope you are ok!?
Seeya

### CODE REVIEW

**Comment by USAMA-app** [comment]
is this updated in nuget package?

**Comment by Phenek** [comment]
Nop but you can compile your own nuget with it.

**Comment by alexrainman** [comment]
Version 1.0.3 should resolve this issue. CarouselView 6.0 will be out soon. I have been working hard on very cool functionality.

**Comment by Phenek** [comment]
Updating circlepageindicator in our project doesn’t work for many people. Like it’s explain in many duplicate issues.

This issue is here since 6months, many people ask for a workaround and here it is.

**Comment by flaviosuardi** [comment]
@alexrainman apply this PR in 5.2.0 version, please 🙏

**Comment by LeoJHarris** [comment]
@Phenek Your PR didnt work for me which XF version are you using in your project.

**Comment by LeoJHarris** [comment]
Hi @alexrainman cool functionality is great! But we really need something that actually works atm which we have been missing for the last couple of months which is blocking issue. Can we a actually expect something? Thanks!

**Comment by Phenek** [comment]
Sorry @LeoJHarris for me it work.
I’m using Xamarin 3.6, And I’m also on Mac.
I can compile only for iOS and Android.

**Comment by LeoJHarris** [comment]
Hi @Phenek can i ask exactly which 3.6 version you are using? Thanks

**Comment by Phenek** [comment]
@LeoJHarris Sorry for the delay 
[Here](https://we.tl/t-02QX3OPJmk) you can download  the [.nupkg](https://we.tl/t-02QX3OPJmk) I compiled it for iOS/Android only, It did not work for UWP.

Please Compile using Android Version (Target Framework) : >= Android 9.0 Pie
it should work with Xamarin.forms >=3.6.0.344457

@alexrainman Hope you good the rest do not count

**Comment by xleon** [comment]
@Phenek 
> Please Compile using Android Version (Target Framework) : >= Android 9.0 Pie
> it should work with Xamarin.forms >=3.6.0.344457

This is a big blocker for our project and I tried your nuget (installing from a local folder repository) but I still get the same error 

```
System.NotSupportedException: Could not activate JNI Handle 0xbec37788 (key_handle 0x7d7fda0) of Java type 'md5cb1a4bab49bfe17ad6c0290694c1d310/CirclePageIndicator' as managed type 'Com.ViewPagerIndicator.CirclePageIndicator'.
```

**Comment by xleon** [comment]
I think this PR is missing updates on nuspec: https://github.com/alexrainman/CarouselView/blob/master/nuget/CarouselView.nuspec#L174

**Comment by alexrainman** [comment]
An updated CirclePageIndicator package will be released with the next CarouselView. Not merging this PR. Thank you for your support.

**Pull request closed without merging**
